# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch:        # Enable manual trigger from the Actions tab
  push:                     # Enable trigger on push to any branch
    branches:
      - '**'

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clean workspace
        run: |
          rm -rf *
          rm -rf .??* || true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for a truly clean clone

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn clean install
